# Generated by Django 5.1.5 on 2025-02-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='name',
            new_name='username',
        ),
    ]
