# Generated by Django 5.1.5 on 2025-02-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0002_rename_name_userdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='designation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
