# Generated by Django 5.1.5 on 2025-03-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0003_userdb_designation_userdb_profileimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
