# Generated by Django 5.1.5 on 2025-03-02 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0004_alter_userdb_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
