# Generated by Django 5.1.5 on 2025-03-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0005_userdb_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='elementsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('divisions', models.CharField(blank=True, max_length=128, null=True)),
                ('images', models.CharField(blank=True, max_length=128, null=True)),
                ('texts', models.CharField(blank=True, max_length=128, null=True)),
                ('projectcreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('projectname', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
