# Generated by Django 5.1.5 on 2025-03-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0006_elementsdb_projectdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdb',
            old_name='username',
            new_name='email',
        ),
    ]
