# Generated by Django 5.1.5 on 2025-03-10 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0007_rename_username_projectdb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='divisionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divname', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('projectname', models.CharField(blank=True, max_length=40, null=True)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('width', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
