# Generated by Django 5.1.5 on 2025-04-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0008_divisiondb_projectdb_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisiondb',
            name='bgcolor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='bodydiv',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='left',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='positionattrib',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='right',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='styling',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
