# Generated by Django 5.1.5 on 2025-04-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0009_divisiondb_bgcolor_divisiondb_bodydiv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisiondb',
            old_name='right',
            new_name='top',
        ),
    ]
