# Generated by Django 5.1.5 on 2025-04-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0010_rename_right_divisiondb_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisiondb',
            old_name='username',
            new_name='email',
        ),
    ]
