# Generated by Django 5.1.5 on 2025-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0011_rename_username_divisiondb_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisiondb',
            name='heightimg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='imagediv',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='imgwidth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='unithimg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='unitwimg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='divisiondb',
            name='bodydiv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='divisiondb',
            name='styling',
            field=models.TextField(blank=True, null=True),
        ),
    ]
