# Generated by Django 5.1.5 on 2025-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0012_divisiondb_heightimg_divisiondb_imagediv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('projectname', models.CharField(blank=True, max_length=40, null=True)),
                ('imagediv', models.ImageField(blank=True, null=True, upload_to='images')),
                ('imgwidth', models.CharField(blank=True, max_length=30, null=True)),
                ('unitwimg', models.CharField(blank=True, max_length=30, null=True)),
                ('heightimg', models.CharField(blank=True, max_length=30, null=True)),
                ('unithimg', models.CharField(blank=True, max_length=30, null=True)),
                ('parent', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inputDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('projectname', models.CharField(blank=True, max_length=40, null=True)),
                ('inputname', models.CharField(blank=True, max_length=30, null=True)),
                ('inputwidth', models.CharField(blank=True, max_length=30, null=True)),
                ('unitwinput', models.CharField(blank=True, max_length=30, null=True)),
                ('heightinput', models.CharField(blank=True, max_length=30, null=True)),
                ('unithinput', models.CharField(blank=True, max_length=30, null=True)),
                ('parent', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='textDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('projectname', models.CharField(blank=True, max_length=40, null=True)),
                ('textcontent', models.CharField(blank=True, max_length=256, null=True)),
                ('textname', models.CharField(blank=True, max_length=30, null=True)),
                ('textwidth', models.CharField(blank=True, max_length=30, null=True)),
                ('unitwtext', models.CharField(blank=True, max_length=30, null=True)),
                ('heighttext', models.CharField(blank=True, max_length=30, null=True)),
                ('unithtext', models.CharField(blank=True, max_length=30, null=True)),
                ('parent', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='heightimg',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='imagediv',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='imgwidth',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='unithimg',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='unitwimg',
        ),
    ]
