# Generated by Django 5.1.5 on 2025-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0013_imagedb_inputdb_textdb_remove_divisiondb_heightimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedb',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputdb',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textdb',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
