# Generated by Django 5.1.5 on 2025-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0014_imagedb_codes_inputdb_codes_textdb_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='elementsDB',
        ),
        migrations.AddField(
            model_name='imagedb',
            name='styling',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputdb',
            name='placeholder',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inputdb',
            name='styling',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='cssstyle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='htmlcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textdb',
            name='styling',
            field=models.TextField(blank=True, null=True),
        ),
    ]
