# Generated by Django 5.1.5 on 2025-04-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0015_delete_elementsdb_imagedb_styling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisiondb',
            old_name='bodydiv',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='bgcolor',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='height',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='left',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='positionattrib',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='top',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='width',
        ),
    ]
