# Generated by Django 5.1.5 on 2025-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0016_rename_bodydiv_divisiondb_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='inheritanceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('projectname', models.CharField(blank=True, max_length=40, null=True)),
                ('child', models.CharField(blank=True, max_length=30, null=True)),
                ('parent', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='divisiondb',
            name='parent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
