# Generated by Django 5.1.5 on 2025-04-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0017_inheritancedb_divisiondb_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedb',
            old_name='imagediv',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='divisiondb',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='imagedb',
            name='heightimg',
        ),
        migrations.RemoveField(
            model_name='imagedb',
            name='imgwidth',
        ),
        migrations.RemoveField(
            model_name='imagedb',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='imagedb',
            name='unithimg',
        ),
        migrations.RemoveField(
            model_name='imagedb',
            name='unitwimg',
        ),
        migrations.RemoveField(
            model_name='inputdb',
            name='heightinput',
        ),
        migrations.RemoveField(
            model_name='inputdb',
            name='inputwidth',
        ),
        migrations.RemoveField(
            model_name='inputdb',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='inputdb',
            name='unithinput',
        ),
        migrations.RemoveField(
            model_name='inputdb',
            name='unitwinput',
        ),
        migrations.RemoveField(
            model_name='textdb',
            name='heighttext',
        ),
        migrations.RemoveField(
            model_name='textdb',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='textdb',
            name='textwidth',
        ),
        migrations.RemoveField(
            model_name='textdb',
            name='unithtext',
        ),
        migrations.RemoveField(
            model_name='textdb',
            name='unitwtext',
        ),
        migrations.AddField(
            model_name='imagedb',
            name='imagename',
            field=models.ImageField(blank=True, max_length=40, null=True, upload_to=''),
        ),
    ]
