# Generated by Django 5.1.5 on 2025-04-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0018_rename_imagediv_imagedb_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisiondb',
            old_name='code',
            new_name='codes',
        ),
    ]
