# Generated by Django 5.1.5 on 2025-04-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0019_rename_code_divisiondb_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='styleDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('projectname', models.CharField(blank=True, max_length=40, null=True)),
                ('LHS', models.CharField(blank=True, max_length=30, null=True)),
                ('RHS', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
