# Generated by Django 5.1.5 on 2025-04-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0020_styledb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisiondb',
            name='styling',
        ),
    ]
