# Generated by Django 5.1.5 on 2025-04-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0021_remove_divisiondb_styling'),
    ]

    operations = [
        migrations.AddField(
            model_name='styledb',
            name='classname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
