# Generated by Django 5.1.5 on 2025-04-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0022_styledb_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedb',
            name='styling',
        ),
        migrations.RemoveField(
            model_name='textdb',
            name='styling',
        ),
        migrations.AddField(
            model_name='inputdb',
            name='inputtype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
