# Generated by Django 5.1.5 on 2025-04-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0023_remove_imagedb_styling_remove_textdb_styling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedb',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='inputdb',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='inputdb',
            name='styling',
        ),
        migrations.RemoveField(
            model_name='textdb',
            name='codes',
        ),
    ]
