# Generated by Django 5.1.5 on 2025-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0024_remove_imagedb_codes_remove_inputdb_codes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisiondb',
            name='codes',
        ),
        migrations.AlterField(
            model_name='imagedb',
            name='imagename',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
