# Generated by Django 5.1.5 on 2026-02-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0025_remove_divisiondb_codes_alter_imagedb_imagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisiondb',
            name='position',
        ),
    ]
