# Generated by Django 5.1.5 on 2026-02-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0026_remove_divisiondb_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='styledb',
            name='Animation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
